### ISSUE TITLE
Bolt driver compatibility!?

### ISSUE THREAD

**Issue by foobargeez** [majensen/rest-neo4p#20]
Hello,
Do you have any plans of adding bolt driver compatibility?

Thanks!

**Comment by majensen** [comment]
I think this would be great, but I thought bolt was proprietary. Please correct me if I’m wrong!

**Comment by majensen** [comment]
Ok, I'm wrong https://boltprotocol.org/v1 . Will need to think about this.

**Comment by foobargeez** [comment]
Saw one for Python -- https://neo4j.com/docs/api/python-driver/current/ and was searching if there is one for Perl.  Wasn't sure if you are already planning for it.  I am happy to contribute anything I could here.

**Comment by johannessen** [comment]
@foobargeez, do you run queries that produce extremely large numbers of result rows? If not, the Bolt protocol probably doesn’t offer particular advantages over the [Transactional HTTP protocol](https://neo4j.com/docs/http-api/current/#http-api-transactional), which both [REST::Neo4p][] and [Neo4j::Driver][] use.

[REST::Neo4p]: https://metacpan.org/pod/REST::Neo4p
[Neo4j::Driver]: https://metacpan.org/release/Neo4j-Driver

I plan to continue working on [Neo4j::Driver][], but likely won’t support Bolt in the near future. What would be needed is a new Perl module implementing Bolt’s low-level nitty-gritty, as documented on <https://boltprotocol.org/v1/>. [Neo4j::Driver][] could then use that new module to contact the Neo4j server using Bolt instead of HTTP.

This doesn’t seem particularly difficult to me, but I lack the time to do it myself (as I don’t have a use case for Bolt myself).

Once such a Bolt module exists for Perl, [REST::Neo4p][] could in principle use either that directly, or use [Neo4j::Driver][] to offer Bolt support. However, my _impression_ is that abandoning the [deprecated Neo4j REST API](https://neo4j.com/docs/rest-docs/current/) would require a complete rewrite of most parts of Neo4p. Alas, that’s a lot of work… :/

**Comment by foobargeez** [comment]
Thanks for the details.  I don't have a specific business/performance requirement to use bolt at the moment.  I am happy to consume REST::Neo4p/Neo4j::Driver (once ready) for now.  The above being said, I will see if I can get a module that deals with Bolt for us to migrate Neo4j::Driver to it.

Closing this (unless you want to keep it open).

**Comment by majensen** [comment]
Been working hard on a wrapper for Bolt using libneo4j-client by @cleishm - hope to push something for beta soon. I think a big refactor is in order, that takes version 3.x as the starting point and uses cypher exclusively.

**Comment by majensen** [comment]
Guys -- it's starting to take shape at https://github.com/majensen/perlbolt
That package is low-level; first thing I want to do with it is use it in a package DBD::Neo4j. 
It seems to work for me -- but I need to handle UTF-8 for it to be complete. Would really appreciate any feedback.

**Comment by johannessen** [comment]
Very interesting!
Do I understand correctly that the Bolt protocol and libneo4j-client only support one open transaction per connection? – Yes, it looks that way.

**Comment by johannessen** [comment]
Thanks to your great work on Neo4j::Bolt, there is now experimental support for Bolt in [Neo4j::Driver](https://metacpan.org/pod/Neo4j::Driver#EXPERIMENTAL-FEATURES), making it possible to run my existing test suite via Bolt:

```bash
git clone https://github.com/johannessen/neo4j-driver-perl && cd neo4j-driver-perl
export TEST_NEO4J_PASSWORD=...
export TEST_NEO4J_SERVER=bolt://localhost
prove t/*
```

Many of the more intricate tests succeed with Neo4j::Bolt. It looks like those of the remaining failures that fall into the domain of Neo4j::Bolt mostly have to do with error handling (I took the liberty of creating [perlbolt issue #2](https://github.com/majensen/perlbolt/issues/2) about this) and Unicode support (which I haven’t had time to really look into).

In my (perhaps not so humble) opinion, a package DBD::Neo4j should eventually use Neo4j::Driver, so that both Bolt and HTTP/HTTPS are supported.

The API of Neo4j::Driver as documented should be stable at this point, but I’ve left in the stern “pre-release” warning for the moment because there is a small chance that minor changes are necessary in order to fully treat Bolt and HTTP as equals. Should you decide to use Neo4j::Driver for DBD::Neo4j, please let me know if you need to use (or even just would like to use) some of the features documented as “experimental.” For some of those I’m on the fence regarding whether or not to keep them. Any feedback or advice would be appreciated.

**Comment by majensen** [comment]
> Thanks to your great work on Neo4j::Bolt, there is now experimental support for Bolt in [Neo4j::Driver](https://metacpan.org/pod/Neo4j::Driver#EXPERIMENTAL-FEATURES), making it possible to run my existing test suite via Bolt:
> 
> ```shell
> git clone https://github.com/johannessen/neo4j-driver-perl && cd neo4j-driver-perl
> export TEST_NEO4J_PASSWORD=...
> export TEST_NEO4J_SERVER=bolt://localhost
> prove t/*
> ```
> 
> Many of the more intricate tests succeed with Neo4j::Bolt. It looks like those of the remaining failures that fall into the domain of Neo4j::Bolt mostly have to do with error handling (I took the liberty of creating [perlbolt issue #2](https://github.com/majensen/perlbolt/issues/2) about this) and Unicode support (which I haven’t had time to really look into).
> 
> In my (perhaps not so humble) opinion, a package DBD::Neo4j should eventually use Neo4j::Driver, so that both Bolt and HTTP/HTTPS are supported.
> 
> The API of Neo4j::Driver as documented should be stable at this point, but I’ve left in the stern “pre-release” warning for the moment because there is a small chance that minor changes are necessary in order to fully treat Bolt and HTTP as equals. Should you decide to use Neo4j::Driver for DBD::Neo4j, please let me know if you need to use (or even just would like to use) some of the features documented as “experimental.” For some of those I’m on the fence regarding whether or not to keep them. Any feedback or advice would be appreciated.



> Very interesting!
> Do I understand correctly that the Bolt protocol and libneo4j-client only support one open transaction per connection? – Yes, it looks that way.

@johannessen - Reading the [protocol doc](https://boltprotocol.org/v1), it looks like each statement is called within its own transaction implicitly - which suggests that failure in any would not affect execution of successful ones. (They talk about a principle they call "pipelining", in which the server collects and runs the statements as they are received, without the client needing to ack a response. So, they recommend the client collect statements and send them all at once, upon a COMMIT) Also, it appears the client can explicitly BEGIN a transaction--looks like only one at a time in this case.

Thanks for your ticket -- given the above, and the protocol's description of failure modes, I'll want to add some controls and error handling for sure (figuring out how libneo4j-client implements these). After that, sounds like I'll want to push Neo4j::Bolt up to CPAN! 

Neo4j::Driver also sounds like a good option -- will get hip to it.

**Comment by johannessen** [comment]
Mark,
sorry for the long delay.

I’ve been thinking about this. I don’t know if you’re still interested in having REST::Neo4p use Neo4::Driver internally. But if so, then with the new Cypher type system implementation, it wouldn’t be difficult to have Neo4j::Driver use custom package names for blessing the Neo4j entities.

For example:
1. client calls `REST::Neo4p::Node->new()`
1. REST::Neo4p sends Cypher `CREATE ...` to Neo4j::Driver
1. Neo4j::Driver returns blessed `REST::Neo4p::Node` object containing data fetched from Neo4j, ready to use

I’m afraid this would still require rewriting *a lot* of Neo4p. Backwards compatibility might be difficult or impossible to achieve. But I guess this might be a possible way forward.

If you are interested, just let me know and I’ll prioritise implementing the hook that you would need for this.

**Comment by majensen** [comment]
@johannessen Now I'm the one who has been offline! But I still want to make this work. It may be holiday time before I get to it, but I would definitely like to see R:N integrated with N:Bolt / N:Driver.  I'm not to worried about back compat--the ecosystem has changed enormously and it's time to get "modern".

**Comment by johannessen** [comment]
I was kinda hoping that Bolt would work now (with Neo4j 3.5), but I keep getting this error:

````perl
use REST::Neo4p 0.4000;
$REST::Neo4p::AGENT_MODULE = "Neo4j::Driver";
REST::Neo4p->connect("bolt://$user:$password\@$host:7687", $user, $password);
# Use of uninitialized value in numeric eq (==) at …/HTTP/Tiny.pm line 615.
# On version pre-check: 599 Internal Exception at …/REST/Neo4p.pm line 181.
````

A naïve solution might be to force the use of the `http` scheme in `get_neo4j_version()`. But depending on how the server is configured, HTTP may not be available at all. So the version pre-check does need to use Bolt in this case – if determining the server version really is required for Bolt.

Simply using Neo4j::Driver’s `$session->server->version()` for the version pre-check would be an easy way to achieve this.

~(However, this probably fails with Neo4j::Driver 0.17+ on Neo4j versions earlier than 2.0. Do you still target 1.x? I can’t really tell from the REST::Neo4p documentation.)~ ← *fixed in Neo4j::Driver 0.1801*

**Comment by majensen** [comment]
@johannessen - yes this is definitely "on the roadmap" - I wanted to get the stake in the ground with a release and then come back and think about bolt. I was a sort of on the fence about doing this in the first refactor, b/c the big selling point is "now it works with v4.0", and as we know, libneo4j-client is not v4 compatible. 

I think I will "sneak in" the bolt feature in the next update (might be able to put some time in over the holiday). I'm also wanting to dig in to libneo4j-client and the bolt spec and see if there is anything I could do there.

**Comment by johannessen** [comment]
If you were in a position to help libneo4j-client along, that’d be fantastic! I’m not sure I could help with that.

But as things stand now with Neo4p, it looks like this line is the only thing that’s blocking Bolt:
https://github.com/majensen/rest-neo4p/blob/497a611e818a56fc9aab7d2fcc507c51bda88c36/lib/REST/Neo4p.pm#L143

Just remove that one line, and Bolt should work with Neo4p (with the limitation inherent in Neo4j::Bolt).

There will still be warnings from the version pre-check though. Perhaps that check should be skipped entirely if the user specifically asks for the Neo4j::Driver agent?

**Comment by foobargeez** [comment]
> I think I will "sneak in" the bolt feature in the next update (might be able to put some time in over the holiday). I'm also wanting to dig in to libneo4j-client and the bolt spec and see if there is anything I could do there.

Thanks, @majensen!

HTTP was slow for me, so switched to Bolt a few months ago via your Neo4j::Bolt (I am still on neo4j v3.5).

libneo4j-client's incompatibility with neo4j v4 is one of the things blocking our upgrade and I really wish I could help with the changes required there :-/

I sincerely hope neo4j would at some point in future release an official C driver to keep it on par with the constant bolt spec changes.

Just wanted to say many thanks for all your and @johannessen work on these modules.

**Comment by foobargeez** [comment]
Just seeing that there is an official Python bolt driver (https://github.com/neo4j/neo4j-python-driver) -- I wonder how much effort it is to have a PP (Pure Perl) driver for bolt.  That removes dependency on C driver (although at the cost of performance) but hopefully faster than HTTP.  Not sure if time and energy is worth to port to PP (have no idea of Perl driver consumption of neo4j at the moment) .. would appreciate your thoughts.

**Comment by johannessen** [comment]
My gut says this energy would be better spent on the C library. After all, there is already HTTP as fall-back for cases where portability is more important than speed.

It’s also not by any means certain that a PP Bolt driver would actually be faster than an HTTP driver with XS JSON decode (which is what we have now).

BTW, Neo4j has just released “Jolt” (JSON Bolt). I’ll be implementing that in Neo4j::Driver. What kind of performance impact that’s gonna have remains to be seen!

**Comment by majensen** [comment]
@foobargeez - yeah I'm inclined to agree with @johannessen - I think it _could_ be done (I'm starting to grok the protocol), but @cleishm has built such maintainable code, that that is probably the quickest win. I would say if "someone" did implement the protocol in PP, we would want to make it pluggable for Neo4j::Driver. 

Jolt sounds pretty interesting, and might be a good compromise.
Another thought I had was to see how the python driver implemented the protocol. Was it pure python?

**Comment by majensen** [comment]
> I was kinda hoping that Bolt would work now (with Neo4j 3.5), but I keep getting this error:
> 
> ```perl
> use REST::Neo4p 0.4000;
> $REST::Neo4p::AGENT_MODULE = "Neo4j::Driver";
> REST::Neo4p->connect("bolt://$user:$password\@$host:7687", $user, $password);
> # Use of uninitialized value in numeric eq (==) at …/HTTP/Tiny.pm line 615.
> # On version pre-check: 599 Internal Exception at …/REST/Neo4p.pm line 181.
> ```
> 
> A naïve solution might be to force the use of the `http` scheme in `get_neo4j_version()`. But depending on how the server is configured, HTTP may not be available at all. So the version pre-check does need to use Bolt in this case – if determining the server version really is required for Bolt.
> 
> Simply using Neo4j::Driver’s `$session->server->version()` for the version pre-check would be an easy way to achieve this.
> 
> ~(However, this probably fails with Neo4j::Driver 0.17+ on Neo4j versions earlier than 2.0. Do you still target 1.x? I can’t really tell from the REST::Neo4p documentation.)~ ← _fixed in Neo4j::Driver 0.1801_

I shied away from simply making Neo4j::Driver the default driver, because of back compatibility. I think there is a shadow user base out there that occasionally reaches out, and those folks may be sticking with older versions of Neo4j because they have used some true REST endpoint features (like batching) or they have taken advantage of the fact that the Agents are subclasses of the HTTP agents (like HTTP::Tiny or Mojo::UserAgent). 
This was my reason for pulling the "bootstrap" version check out and making it independent from Agents themselves, and hitting the endpoints directly.

**Comment by johannessen** [comment]
> I shied away from simply making Neo4j::Driver the default driver, […]

Right. The way you built it now, the older agents will remain available for users who do need them, independent of what the default is. That seems sensible! And the “default” decision is not an easy one. I mean, obviously the defaults should work with the latest Neo4j version. At the same time, changing the defaults tends to break existing use. The independent version pre-check you added seems an elegant way around that issue. It just needs to work for Bolt as well, is all.

> This was my reason for pulling the "bootstrap" version check out and making it independent from Agents themselves, and hitting the endpoints directly.

It should be safe now to use Neo4j::Driver for that version check, no matter which Agent / which Neo4j version / which protocol is in play.

But fixing `get_neo4j_version()` to work for Bolt should be easy, too.


> […] I think it _could_ be done (I'm starting to grok the protocol), […]
> Another thought I had was to see how the python driver implemented the protocol. Was it pure python?

Yes, it was.

Bolt::PP absolutely *could* be done. Just needs somebody to do it.
