### ISSUE TITLE
Initial implementation landed, see ["Type system customisation" in Neo4j::Driver 0.14](https://metacpan.org/pod/release/AJNN/Neo4j-Driver-0.14/lib/Neo4j/Driver.pm#Type-system-customisation). Would @majensen consider this suitable for adapting REST::Neo4p to use Neo4j::Driver? Are any other changes to Neo4j::Driver necessary (or perhaps just useful)?

### ISSUE THREAD

**Issue by majensen** [majensen/rest-neo4p#21]
Initial implementation landed, see ["Type system customisation" in Neo4j::Driver 0.14](https://metacpan.org/pod/release/AJNN/Neo4j-Driver-0.14/lib/Neo4j/Driver.pm#Type-system-customisation). Would @majensen consider this suitable for adapting REST::Neo4p to use Neo4j::Driver? Are any other changes to Neo4j::Driver necessary (or perhaps just useful)?

_Originally posted by @johannessen in https://github.com/johannessen/neo4j-driver-perl/issues/4#issuecomment-568130218_

**Comment by majensen** [comment]
@johannessen -- did we cover everything you needed here? thanks

**Comment by johannessen** [comment]
Not quite sure what you’re asking. But on the matter of Neo4j versions and Perl, consider these three projects:
* REST::Neo4p – currently supports Neo4j 1+2+3
* Neo4j::Driver – currently supports Neo4j 2+3+4
* libneo4j-client – currently supports Neo4j 3

I’d expect that Neo4j 4 support for REST::Neo4p amounts to a complete rewrite. Since all of the old Neo4j 1+2 era code can probably be removed in the process, this may be easier than it looks, but it’s still a lot of work.

I think you can rewrite Neo4p today to use Neo4j::Driver, and it should work just fine with Neo4j 2+3+4 via HTTP (and also Neo4j 3 via Bolt). In theory, using Neo4j::Driver should help to isolate Neo4p from future changes in the Neo4j server. For implementation pointers, see https://github.com/majensen/rest-neo4p/issues/20#issuecomment-543798074 and https://github.com/johannessen/neo4j-driver-perl/issues/4.

However, given the way Neo4p accesses Neo4j about individual pieces of information so often, I’d expect that you’d probably want Bolt support in order to realise Neo4p’s full potential. Frequent server roundtrips on HTTP are just too slow. (As you may recall, this was the reason why I found that I had to drop Neo4p and write Neo4j::Driver in the first place.) To get Bolt support, you *can* have Neo4p just use Neo4j::Driver and simply let the user specify a `bolt:` URL. But it *may* be easier for you to drop HTTP support entirely, skip Neo4j::Driver and have Neo4p use Neo4j::Bolt directly and exclusively. Of course, as long as libneo4j-client only supports Neo4j 3, this wouldn’t really help that much…

**Comment by majensen** [comment]
With https://metacpan.org/pod/REST::Neo4p v0.4000, I think we can close this issue. The solution was different from https://github.com/majensen/rest-neo4p/issues/21#issuecomment-677989024, but I was going for a "drop-in" compatibility, preserving the illusion of a REST endpoint. This might be the final stage of REST::Neo4p, but it should work for a while.
